/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgricultorDashboardRouteImport } from './routes/agricultor.dashboard'
import { Route as AgricultorPedidosRouteImport } from './routes/agricultor.pedidos'
import { Route as AgricultorPerfilRouteImport } from './routes/agricultor.perfil'
import { Route as ConsumidorCarrinhoRouteImport } from './routes/consumidor.carrinho'
import { Route as ConsumidorCheckoutRouteImport } from './routes/consumidor.checkout'
import { Route as ConsumidorHomeRouteImport } from './routes/consumidor.home'
import { Route as ConsumidorPedidosRouteImport } from './routes/consumidor.pedidos'
import { Route as ConsumidorPerfilRouteImport } from './routes/consumidor.perfil'
import { Route as AgricultorProdutosIndexRouteImport } from './routes/agricultor.produtos.index'
import { Route as AgricultorProdutosNovoRouteImport } from './routes/agricultor.produtos.novo'
import { Route as ConsumidorProdutosIdRouteImport } from './routes/consumidor.produtos.$id'
import { Route as AgricultorProdutosIdEditarRouteImport } from './routes/agricultor.produtos.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorDashboardRoute = AgricultorDashboardRouteImport.update({
  id: '/agricultor/dashboard',
  path: '/agricultor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorPedidosRoute = AgricultorPedidosRouteImport.update({
  id: '/agricultor/pedidos',
  path: '/agricultor/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorPerfilRoute = AgricultorPerfilRouteImport.update({
  id: '/agricultor/perfil',
  path: '/agricultor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorCarrinhoRoute = ConsumidorCarrinhoRouteImport.update({
  id: '/consumidor/carrinho',
  path: '/consumidor/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorCheckoutRoute = ConsumidorCheckoutRouteImport.update({
  id: '/consumidor/checkout',
  path: '/consumidor/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorHomeRoute = ConsumidorHomeRouteImport.update({
  id: '/consumidor/home',
  path: '/consumidor/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorPedidosRoute = ConsumidorPedidosRouteImport.update({
  id: '/consumidor/pedidos',
  path: '/consumidor/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorPerfilRoute = ConsumidorPerfilRouteImport.update({
  id: '/consumidor/perfil',
  path: '/consumidor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorProdutosIndexRoute = AgricultorProdutosIndexRouteImport.update({
  id: '/agricultor/produtos/',
  path: '/agricultor/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorProdutosNovoRoute = AgricultorProdutosNovoRouteImport.update({
  id: '/agricultor/produtos/novo',
  path: '/agricultor/produtos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorProdutosIdRoute = ConsumidorProdutosIdRouteImport.update({
  id: '/consumidor/produtos/$id',
  path: '/consumidor/produtos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgricultorProdutosIdEditarRoute =
  AgricultorProdutosIdEditarRouteImport.update({
    id: '/agricultor/produtos/$id/editar',
    path: '/agricultor/produtos/$id/editar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/educacao': typeof EducacaoRoute
  '/login': typeof LoginRoute
  '/agricultor/dashboard': typeof AgricultorDashboardRoute
  '/agricultor/pedidos': typeof AgricultorPedidosRoute
  '/agricultor/perfil': typeof AgricultorPerfilRoute
  '/consumidor/carrinho': typeof ConsumidorCarrinhoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/home': typeof ConsumidorHomeRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/agricultor/produtos/novo': typeof AgricultorProdutosNovoRoute
  '/consumidor/produtos/$id': typeof ConsumidorProdutosIdRoute
  '/agricultor/produtos/': typeof AgricultorProdutosIndexRoute
  '/agricultor/produtos/$id/editar': typeof AgricultorProdutosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/educacao': typeof EducacaoRoute
  '/login': typeof LoginRoute
  '/agricultor/dashboard': typeof AgricultorDashboardRoute
  '/agricultor/pedidos': typeof AgricultorPedidosRoute
  '/agricultor/perfil': typeof AgricultorPerfilRoute
  '/consumidor/carrinho': typeof ConsumidorCarrinhoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/home': typeof ConsumidorHomeRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/agricultor/produtos/novo': typeof AgricultorProdutosNovoRoute
  '/consumidor/produtos/$id': typeof ConsumidorProdutosIdRoute
  '/agricultor/produtos': typeof AgricultorProdutosIndexRoute
  '/agricultor/produtos/$id/editar': typeof AgricultorProdutosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/educacao': typeof EducacaoRoute
  '/login': typeof LoginRoute
  '/agricultor/dashboard': typeof AgricultorDashboardRoute
  '/agricultor/pedidos': typeof AgricultorPedidosRoute
  '/agricultor/perfil': typeof AgricultorPerfilRoute
  '/consumidor/carrinho': typeof ConsumidorCarrinhoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/home': typeof ConsumidorHomeRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/agricultor/produtos/novo': typeof AgricultorProdutosNovoRoute
  '/consumidor/produtos/$id': typeof ConsumidorProdutosIdRoute
  '/agricultor/produtos/': typeof AgricultorProdutosIndexRoute
  '/agricultor/produtos/$id/editar': typeof AgricultorProdutosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/educacao'
    | '/login'
    | '/agricultor/dashboard'
    | '/agricultor/pedidos'
    | '/agricultor/perfil'
    | '/consumidor/carrinho'
    | '/consumidor/checkout'
    | '/consumidor/home'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/agricultor/produtos/novo'
    | '/consumidor/produtos/$id'
    | '/agricultor/produtos/'
    | '/agricultor/produtos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/educacao'
    | '/login'
    | '/agricultor/dashboard'
    | '/agricultor/pedidos'
    | '/agricultor/perfil'
    | '/consumidor/carrinho'
    | '/consumidor/checkout'
    | '/consumidor/home'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/agricultor/produtos/novo'
    | '/consumidor/produtos/$id'
    | '/agricultor/produtos'
    | '/agricultor/produtos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/alterar-senha'
    | '/cadastro'
    | '/educacao'
    | '/login'
    | '/agricultor/dashboard'
    | '/agricultor/pedidos'
    | '/agricultor/perfil'
    | '/consumidor/carrinho'
    | '/consumidor/checkout'
    | '/consumidor/home'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/agricultor/produtos/novo'
    | '/consumidor/produtos/$id'
    | '/agricultor/produtos/'
    | '/agricultor/produtos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  CadastroRoute: typeof CadastroRoute
  EducacaoRoute: typeof EducacaoRoute
  LoginRoute: typeof LoginRoute
  AgricultorDashboardRoute: typeof AgricultorDashboardRoute
  AgricultorPedidosRoute: typeof AgricultorPedidosRoute
  AgricultorPerfilRoute: typeof AgricultorPerfilRoute
  ConsumidorCarrinhoRoute: typeof ConsumidorCarrinhoRoute
  ConsumidorCheckoutRoute: typeof ConsumidorCheckoutRoute
  ConsumidorHomeRoute: typeof ConsumidorHomeRoute
  ConsumidorPedidosRoute: typeof ConsumidorPedidosRoute
  ConsumidorPerfilRoute: typeof ConsumidorPerfilRoute
  AgricultorProdutosNovoRoute: typeof AgricultorProdutosNovoRoute
  ConsumidorProdutosIdRoute: typeof ConsumidorProdutosIdRoute
  AgricultorProdutosIndexRoute: typeof AgricultorProdutosIndexRoute
  AgricultorProdutosIdEditarRoute: typeof AgricultorProdutosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/dashboard': {
      id: '/agricultor/dashboard'
      path: '/agricultor/dashboard'
      fullPath: '/agricultor/dashboard'
      preLoaderRoute: typeof AgricultorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/pedidos': {
      id: '/agricultor/pedidos'
      path: '/agricultor/pedidos'
      fullPath: '/agricultor/pedidos'
      preLoaderRoute: typeof AgricultorPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/perfil': {
      id: '/agricultor/perfil'
      path: '/agricultor/perfil'
      fullPath: '/agricultor/perfil'
      preLoaderRoute: typeof AgricultorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/carrinho': {
      id: '/consumidor/carrinho'
      path: '/consumidor/carrinho'
      fullPath: '/consumidor/carrinho'
      preLoaderRoute: typeof ConsumidorCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/checkout': {
      id: '/consumidor/checkout'
      path: '/consumidor/checkout'
      fullPath: '/consumidor/checkout'
      preLoaderRoute: typeof ConsumidorCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/home': {
      id: '/consumidor/home'
      path: '/consumidor/home'
      fullPath: '/consumidor/home'
      preLoaderRoute: typeof ConsumidorHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/pedidos': {
      id: '/consumidor/pedidos'
      path: '/consumidor/pedidos'
      fullPath: '/consumidor/pedidos'
      preLoaderRoute: typeof ConsumidorPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/perfil': {
      id: '/consumidor/perfil'
      path: '/consumidor/perfil'
      fullPath: '/consumidor/perfil'
      preLoaderRoute: typeof ConsumidorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/produtos/': {
      id: '/agricultor/produtos/'
      path: '/agricultor/produtos'
      fullPath: '/agricultor/produtos/'
      preLoaderRoute: typeof AgricultorProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/produtos/novo': {
      id: '/agricultor/produtos/novo'
      path: '/agricultor/produtos/novo'
      fullPath: '/agricultor/produtos/novo'
      preLoaderRoute: typeof AgricultorProdutosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/produtos/$id': {
      id: '/consumidor/produtos/$id'
      path: '/consumidor/produtos/$id'
      fullPath: '/consumidor/produtos/$id'
      preLoaderRoute: typeof ConsumidorProdutosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultor/produtos/$id/editar': {
      id: '/agricultor/produtos/$id/editar'
      path: '/agricultor/produtos/$id/editar'
      fullPath: '/agricultor/produtos/$id/editar'
      preLoaderRoute: typeof AgricultorProdutosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  CadastroRoute: CadastroRoute,
  EducacaoRoute: EducacaoRoute,
  LoginRoute: LoginRoute,
  AgricultorDashboardRoute: AgricultorDashboardRoute,
  AgricultorPedidosRoute: AgricultorPedidosRoute,
  AgricultorPerfilRoute: AgricultorPerfilRoute,
  ConsumidorCarrinhoRoute: ConsumidorCarrinhoRoute,
  ConsumidorCheckoutRoute: ConsumidorCheckoutRoute,
  ConsumidorHomeRoute: ConsumidorHomeRoute,
  ConsumidorPedidosRoute: ConsumidorPedidosRoute,
  ConsumidorPerfilRoute: ConsumidorPerfilRoute,
  AgricultorProdutosNovoRoute: AgricultorProdutosNovoRoute,
  ConsumidorProdutosIdRoute: ConsumidorProdutosIdRoute,
  AgricultorProdutosIndexRoute: AgricultorProdutosIndexRoute,
  AgricultorProdutosIdEditarRoute: AgricultorProdutosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
